USE MASTER
GO 

CREATE DATABASE [BDClinica]
GO

USE BDClinica
GO

CREATE TABLE PROVINCIA (
    IdProvincia INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,

    CONSTRAINT PK_PROVINCIA PRIMARY KEY (IdProvincia)
);
GO

CREATE TABLE LOCALIDAD (
    IdLocalidad INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    IdProvincia INT NOT NULL,
    
    CONSTRAINT PK_LOCALIDAD PRIMARY KEY (IdLocalidad),
    CONSTRAINT FK_LOCALIDAD FOREIGN KEY (IdProvincia) REFERENCES PROVINCIA (IdProvincia)
);

CREATE TABLE USUARIO(
    IdUsuario INT IDENTITY(1,1),
    NombreUsuario VARCHAR(50) NOT NULL UNIQUE,
    Contrasena VARCHAR(8) NOT NULL,
    TipoUsuario VARCHAR(20) NOT NULL,

    CONSTRAINT PK_USUARIO PRIMARY KEY (IdUsuario)
);

CREATE TABLE PACIENTE(
    DNI CHAR(8),
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Sexo CHAR(1),
    Nacionalidad VARCHAR(50),
    FechaNacimiento DATE,
    Direccion VARCHAR(100),
    CorreoElectronico VARCHAR(100),
    Telefono VARCHAR(20),
    IdLocalidad INT NOT NULL,

    CONSTRAINT PK_PACIENTE PRIMARY KEY (DNI),
    CONSTRAINT FK_PACIENTE_LOCALIDAD FOREIGN KEY (IdLocalidad) REFERENCES Localidad(IdLocalidad)
);

CREATE TABLE ESPECIALIDAD(
    IdEspecialidad INT,
    Nombre VARCHAR(100) NOT NULL,

    CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (IdEspecialidad)
);

CREATE TABLE MEDICO(
    Legajo INT,
    DNI CHAR(8) NOT NULL UNIQUE,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Sexo CHAR(1),
    Nacionalidad VARCHAR(50),
    FechaNacimiento DATE,
    Direccion VARCHAR(100),
    CorreoElectronico VARCHAR(100),
    Telefono VARCHAR(20),

    IdLocalidad INT NOT NULL,
    IdEspecialidad INT NOT NULL,
    IdUsuario INT UNIQUE,

    CONSTRAINT PK_MEDICO PRIMARY KEY (Legajo),
    CONSTRAINT FK_MEDICO_LOCALIDAD FOREIGN KEY (IdLocalidad) REFERENCES Localidad(IdLocalidad),
    CONSTRAINT FK_MEDICO_ESPECIALIDAD FOREIGN KEY (IdEspecialidad) REFERENCES Especialidad(IdEspecialidad),
    CONSTRAINT FK_MEDICO_IDUSUARIO FOREIGN KEY (IdUsuario)  REFERENCES Usuario(IdUsuario)
);


INSERT INTO PROVINCIA (IdProvincia, Nombre) 
SELECT 1 ,'Buenos Aires' UNION
SELECT 2, 'Catamarca' UNION
SELECT 3, 'Chaco' UNION
SELECT 4, 'Chubut' UNION
SELECT 5, 'Ciudad Autónoma de Buenos Aires' UNION
SELECT 6, 'Córdoba' UNION
SELECT 7, 'Corrientes' UNION
SELECT 8, 'Entre Ríos' UNION
SELECT 9, 'Formosa' UNION
SELECT 10, 'Jujuy' UNION
SELECT 11, 'La Pampa' UNION
SELECT 12, 'La Rioja' UNION
SELECT 13, 'Mendoza' UNION
SELECT 14, 'Misiones' UNION
SELECT 15, 'Neuquén' UNION
SELECT 16, 'Río Negro' UNION
SELECT 17, 'Salta' UNION
SELECT 18, 'San Juan' UNION
SELECT 19, 'San Luis' UNION
SELECT 20, 'Santa Cruz' UNION
SELECT 21, 'Santa Fe' UNION
SELECT 22, 'Santiago del Estero' UNION
SELECT 23, 'Tierra del Fuego' UNION
SELECT 24, 'Tucumán';
GO